version: '3.8'

services:
  rms-db-migrate:
    image: busybox
    volumes:
      - ./data:/source:ro
      - rms-db-volume:/destination/
    command: >
      sh -c "cp -r /source/* /destination/ &&
             chmod -R 755 /destination/"

  rms-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - "8056:8056"
      - "8057:8057"
    volumes:
      - rms-db-volume:/app/data
    environment:
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      SECRET_KEY: your-secret-key-here
      LOG_LEVEL: INFO
    restart: unless-stopped
    depends_on:
      - db

volumes:
  rms-db-volume:
    external: true

